### ISSUE TITLE
CCM Client instructions failure because of missing freeswitch-mod-smpp package

### ISSUE THREAD

**Issue by mferland** [facebookincubator/CommunityCellularManager#28]
I am currently following the client instructions and when issuing the `apt-get install endaga-osmocom` I get:

~~~~
root@endaga-client-osmocom:~# apt-get install endaga-osmocom
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 endaga-osmocom : Depends: freeswitch-mod-smpp but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
~~~~

I gave a quick look at the FreeSwitch package feed and noticed that this package is missing for some reason...

**Comment by 9muir** [comment]
there are a number of factors that cause this, but it is partly due to dependencies being done in different ways between CCM and Freeswitch: the top-level CCM package for Osmocom currently just depends on FS without specifying a specific version, whereas FS version X specifies that other packages should be the same version. That means that when FS gets upgraded to X the `freeswitch-mod-smpp` version required also changes to X, but since `freeswitch-mod-smpp` is not built as part of the default FS build, there will not typically be a new version of that package.

We're in the process of fixing this, most likely by just pinning to a specific version of FS.

**Comment by mferland** [comment]
Nice. Thanks for the feedback.

In the mean time I was able the manually compile the FS deb packages along with the `freeswitch-mod-smpp` module and install these manually.

**Comment by 9muir** [comment]
Yeah, manual compilation has been our workaround too.

**Comment by kkroo** [comment]
The issue we were facing was that freeswitch doesn't build mod_smpp and we were releasing it ourselves. However, each time freeswitch would release a new version, our mod_smpp would become uninstallable by apt. After talking with the guys at FS, we are now hosting freeswitch in our repo to give us more control over releases. This should now be fixed
